# Run the playbook with:
# ansible-playbook -i invfile playbooks/4.vault/vault_testing.yml --ask-vault-pass -v

---
- name: Configure AWS Credentials and Run AWS CLI Commands
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  serial: 3
  vars:
    user_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38303132623738306339373531666437393130346136653330336332356236373963313061633963
      6462373238343432636634626563393333666661336463370a383937366238393735396133316631
      35373433313266656534383031633762386165666161373032303339626335356636616662363565
      3134636236613538300a636465333464323737653931316434303335636432386235343934313061
      6364

  tasks:
    - name: Ensure .aws directory exists
      file:
        path: /root/.aws
        state: directory
        mode: "0700"

    - name: Copy AWS credentials file to target hosts
      copy:
        src: /tmp/aws_creds  # Ensure this file exists before running the playbook
        dest: /root/.aws/credentials
        owner: root
        group: root
        mode: "0600"

    - name: Configure AWS region
      copy:
        dest: /root/.aws/config
        content: |
          [default]
          region = us-east-1
        owner: root
        group: root
        mode: "0600"

    - name: Verify AWS CLI authentication
      command: aws sts get-caller-identity --output json
      register: aws_identity
      ignore_errors: yes

    - name: Debug AWS Identity Output
      debug:
        var: aws_identity.stdout_lines

    - name: Check S3 Buckets
      command: aws s3 ls --output json
      register: buckets
      ignore_errors: yes

    - name: Print S3 Bucket Names
      debug:
        var: buckets.stdout_lines

    - name: Get VPCs from AWS CLI
      command: aws ec2 describe-vpcs --output json
      register: vpcs_raw
      ignore_errors: yes

    - name: Extract VPC IDs
      set_fact:
        vpc_ids: "{{ vpcs_raw.stdout | from_json | json_query('Vpcs[].VpcId') }}"

    - name: Print VPC IDs
      debug:
        var: vpc_ids
