---
- name: Playbook to install generic tools
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  vars:
    TFROM: 1.11.2
  tasks:
    - name: check the hostnames
      shell: cat /etc/lsb-release
    - name: perform apt update
      shell: apt-get update
    - name: install tools
      shell: apt-get install -y unzip jq stress net-tools
